version: "3.8"

services:

  react-app:
    container_name: rrk-test1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app
      - react-app-data:/app/node_modules
    depends_on:
      - keycloack

  keycloack:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    volumes:
      - ./data/keycloak:/tmp

volumes:
  react-app-data: